[lint.per-file-ignores]
"src/sql/datasets/psa_psgc/bronze/psa_psgc.py" = ["F821"]
"src/sql/datasets/psa_psgc/extract/psa_psgc_ingest.py" = ["F821"]
"src/sql/datasets/psa_psgc/lgu_master.py" = ["F821"]